name: finanz_notiz_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/finanz.jpeg
    - assets/notiz.png
    - assets/notiz1.png

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.6
